apiVersion: app/v1
kind: Deployment
metada: 
  name: auth-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metada:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: ahmadsalahuddeen/auth
---
apiVersion: v1
kind: Service
metada:
  name: auth-srv  
spec:
  selector: 
    app: app
  ports:
    - name: auth
      protocol: TCP
      port: 3000
      targetPort: 3000